# ~/ros2_ws/src/robot_bringup/config/ekf.yaml
ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # IMU input
    # This configuration uses orientation (roll, pitch, yaw), angular velocity (vroll, vpitch, vyaw),
    # and linear acceleration (ax, ay, az) from the IMU to improve the state estimate.
    imu0: imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    # Wheel odometry input
    # This section has been commented out to disable wheel odometry input.
    # odom0: /odom/wheel
    # odom0_config: [true,  true,  false,
    #                false, false, false,
    #                false, false, false,
    #                false, false, false,
    #                false, false, false]
    # odom0_differential: false
    # odom0_queue_size: 10

    # Process noise covariances
    process_noise_covariance: [0.05, 0,    0,    0,    0,    0,    0,     0,    0,    0,    0,    0,    0,    0,    0,
                               0,    0.05, 0,    0,    0,    0,    0,     0,    0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0.06, 0,    0,    0,    0,     0,    0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0.03, 0,    0,    0,     0,    0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0.03, 0,    0,     0,    0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0.06, 0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0.025, 0,    0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0.025, 0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,    0.04, 0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,    0,    0.01, 0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,    0,    0,    0.01, 0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,    0,    0,    0,    0.02, 0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,    0,    0,    0,    0,    0.02, 0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,    0,    0,    0,    0,    0,    0.04, 0,
                               0,    0,    0,    0,    0,    0,    0,     0,    0,    0,    0,    0,    0,    0,    0.015]

    # Initial estimate covariances
    initial_state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    initial_estimate_covariance: [0.1, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                 0,    0.1,  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                 0,    0,    0.1,  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                 0,    0,    0,    0.1,  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                 0,    0,    0,    0,    0.1,  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                 0,    0,    0,    0,    0,    0.1,  0,    0,    0,    0,    0,    0,    0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0.1,  0,    0,    0,    0,    0,    0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0.1,  0,    0,    0,    0,    0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0.1,  0,    0,    0,    0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0.1,  0,    0,    0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0.1,  0,    0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0.1,  0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0.1,  0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0.1,  0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0.1]
