# Remove AMCL entirely since we're using SLAM
# amcl:  # REMOVE THIS SECTION COMPLETELY

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_nav_to_pose_bt_xml: "navigate_to_pose_w_replanning_and_recovery.xml"
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_recovery_node_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core/DWBLocalPlanner"
      # Add DWB parameters here
      max_vel_x: 0.3
      min_vel_x: -0.3
      max_vel_y: 0.0
      min_vel_y: 0.0
      max_rot_vel: 0.5
      min_rot_vel: -0.5
      acc_lim_x: 0.5
      acc_lim_y: 0.0
      acc_lim_theta: 0.7

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: nav2_navfn_planner::NavfnPlanner
      tolerance: 0.2  # Increased tolerance for SLAM odometry

smoother_server:
  ros__parameters:
    use_sim_time: false
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: nav2_smoother/SimpleSmoother

behavior_server:
  ros__parameters:
    use_sim_time: false

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    stop_on_failure: false

# Costmaps - CRITICAL FRAME UPDATES
global_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_footprint  # CHANGED from base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    rolling_window: false
    width: 20.0
    height: 20.0
    resolution: 0.05
    robot_radius: 0.20
    footprint: "[[0.25, 0.20], [0.25, -0.20], [-0.25, -0.20], [-0.25, 0.20]]"
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]  # Added static_layer

    static_layer:
      plugin: nav2_costmap_2d::StaticLayer
      map_topic: /map
      subscribe_to_updates: true
      track_unknown_space: true
      use_maximum: false
      trinary_costmap: true

    obstacle_layer:
      plugin: nav2_costmap_2d::ObstacleLayer
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 1.0
        clearing: true
        marking: true
        data_type: LaserScan
        obstacle_max_range: 6.0
        raytrace_max_range: 7.0
        inf_is_valid: false
      combination_method: 1

    inflation_layer:
      plugin: nav2_costmap_2d::InflationLayer
      inflation_radius: 0.6
      cost_scaling_factor: 3.0

local_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: odom
    robot_base_frame: base_footprint  # CHANGED from base_link
    update_frequency: 10.0
    publish_frequency: 5.0
    rolling_window: true
    width: 5.0
    height: 5.0
    resolution: 0.05
    robot_radius: 0.20
    footprint: "[[0.25, 0.20], [0.25, -0.20], [-0.25, -0.20], [-0.25, 0.20]]"
    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
      plugin: nav2_costmap_2d::ObstacleLayer
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 1.0
        clearing: true
        marking: true
        data_type: LaserScan
        obstacle_max_range: 5.0
        raytrace_max_range: 6.0
        inf_is_valid: false

    inflation_layer:
      plugin: nav2_costmap_2d::InflationLayer
      inflation_radius: 0.5
      cost_scaling_factor: 3.0

# Lifecycle manager to bring up Nav2 servers
lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - controller_server
      - planner_server
      - smoother_server
      - bt_navigator
      - waypoint_follower
      - behavior_server
