slam_toolbox:
  ros__parameters:
    # Basic configuration
    use_sim_time: false

    # Frame configuration - CRITICAL: Use base_footprint for Nav2 compatibility
    base_frame: base_footprint
    odom_frame: odom
    map_frame: map

    # Topic configuration
    scan_topic: /scan
    mode: mapping  # mapping for online SLAM

    # ODOMETRY PUBLICATION - THIS IS WHAT YOU'RE MISSING!
    publish_odom: true              # Enable odometry publication
    publish_odom_tf: true           # Enable odometry TF publication
    odom_frame: odom                # Odom frame name
    map_frame: map                  # Map frame name
    base_frame: base_footprint      # Base frame name

    # Laser parameters
    max_laser_range: 8.0   # Match your RPLidar A1 range
    minimum_time_interval: 0.5
    transform_publish_period: 0.02

    # Map parameters
    resolution: 0.05
    map_update_interval: 5.0

    # Scan matching parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.0872665  # 5 degrees in radians

    # Loop closure parameters
    do_loop_closing: true
    loop_search_maximum_distance: 4.0
    loop_search_space_resolution: 0.05

    # Optimization parameters
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT

    # Performance tuning
    throttle_scans: 1
    stack_size: 4000000

    # IMU integration (if available)
    use_imu: false  # Set to true if you want to fuse IMU data

    # Debug
    debug_logging: false
